### ISSUE TITLE
yarn generate:readme with inconsistent results

### ISSUE THREAD

**Issue by tillwestpfahl** [mittwald/cli#654]
> [niristius](https://github.com/niristius) commented [4 days ago](https://github.com/mittwald/cli/pull/650#issue-2402989189)
> So I deleted the old branch since it was kinda stale and I am still trying to understand Node, yarn and oclif a bit more.
> And since the changes are rather trivial I started over.
> 
> Sadly the yarn generate:readme command still adds newlines where they dont belong.
> 
> I tried
> 
> using Node 18, 20, 22
> using oclif 4.14, 4.13, 4.12, 4.10, 3.17, 3.16, 3.15, 3.14
> still no cigar.
> @martin-helmich please advise

I have the same exact problem ([see here](https://github.com/mittwald/cli/actions/runs/9938894314/job/27452328300)). Also for some reason, the generated readme looks entirely different after a fresh repo clone.

Also `yarn format` changes the README formatting yet another way (which to be fair, is probably expected).

**Comment by niristius** [comment]
This PR is stuggling with this aswell: https://github.com/mittwald/cli/pull/465

**Comment by niristius** [comment]
And this one aswell: https://github.com/mittwald/cli/pull/687

**Comment by niristius** [comment]
and also these
https://github.com/mittwald/cli/pull/699
https://github.com/mittwald/cli/pull/700

**Comment by martin-helmich** [comment]
Did some digging on this; apparently, the output differs, depending on whether you're invoking `yarn generate:readme` or calling `./node_modules/.bin/oclif readme` directly. Will investigate further. 🕵️‍♂️
